### ISSUE TITLE
文档协作计划

### ISSUE THREAD

**Issue by airyland** [vuxjs/vux-doc#1]
个人时间不够，现在完成了基本的文档结构和demo的运行，希望大家一起完善。
流程：认领后在该issue评论里注明认领的组件名字，防止其他同学重复认领。
未写文档的组件列表可以clone到本地查看。

**Comment by airyland** [comment]
@erguotou520 
@lichunqiang 
@graysheeep

各位有时间来帮忙～

**Comment by graysheeep** [comment]
@airyland OK我重新pull一下

**Comment by erguotou520** [comment]
认领
- [x] x-textarea

**Comment by graysheeep** [comment]
- [x] 3.5 Actionsheet
- [x] 5.2 XInput
- [x] 5.8 Rater
- [x] 5.9 Calendar-inline
- [x] 5.10 Radio
- [x] 5.11 Calendar 
- [x] 5.12 Datetime

**Comment by airyland** [comment]
我处理弹窗相关的组件
- [x] Alert
- [x] Popup
- [x] Confirm
- [x] Toast

**Comment by lichunqiang** [comment]
挑几个简单的，练练手
- [ ] Search 搜索
- [x] Divider横向分割线
- [x] checklist
- [x] number
- [x] range

---
- [x] Sticky
- [x] Popup
- [x] Progress
- [x] Swiper
