### ISSUE TITLE
文档未编写规整及校验

### ISSUE THREAD

**Issue by lichunqiang** [vuxjs/vux-doc#12]
https://github.com/airyland/vux/commit/9d7ac884385038bfd9786b61850de092c386a5bf

所以是不是规整下，现在还有哪些文档没做。然后在做统一的文档规范和校验

**Comment by airyland** [comment]
👍  需要的，我抓紧时间

**Comment by airyland** [comment]
文档参数说明参考形式，把Prop Slot Event 分Tab显示

![image](https://cloud.githubusercontent.com/assets/559179/15322022/cae394ce-1c6c-11e6-8c64-7ebc4f40ed9e.png)

**Comment by lichunqiang** [comment]
看起来很清晰 :+1:
